/** @file
  Install ACPI tables generated by libkrun for x86_64 guests.

  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

#include <IndustryStandard/Acpi.h>
#include <IndustryStandard/Krun.h>
#include <Library/BaseLib.h>
#include <Library/BaseMemoryLib.h>
#include <Library/DebugLib.h>
#include <Library/UefiBootServicesTableLib.h>
#include <Protocol/AcpiTable.h>
#include <Guid/Acpi.h>
#include "AcpiPlatform.h"

STATIC BOOLEAN
ChecksumIsValid (
  IN CONST VOID  *Buffer,
  IN UINTN       Length
  )
{
  CONST UINT8  *Byte;
  UINT8        Sum;

  Byte = Buffer;
  Sum  = 0;

  while (Length-- != 0) {
    Sum = (UINT8)(Sum + *Byte++);
  }

  return Sum == 0;
}

EFI_STATUS
EFIAPI
InstallKrunTables (
  IN EFI_ACPI_TABLE_PROTOCOL  *AcpiProtocol
  )
{
  EFI_ACPI_2_0_ROOT_SYSTEM_DESCRIPTION_POINTER  *Rsdp;
  EFI_ACPI_DESCRIPTION_HEADER                   *Xsdt;
  EFI_ACPI_DESCRIPTION_HEADER                   *Table;
  EFI_ACPI_DESCRIPTION_HEADER                   *Dsdt;
  EFI_ACPI_2_0_FIXED_ACPI_DESCRIPTION_TABLE     *Fadt;
  UINT64                                        *Entry;
  UINTN                                         EntryCount;
  UINTN                                         Index;
  UINTN                                         TableHandle;
  EFI_STATUS                                    Status;

  Rsdp = (VOID *)(UINTN)KRUN_ACPI_RSDP_ADDRESS;

  if ((Rsdp->Signature != EFI_ACPI_2_0_ROOT_SYSTEM_DESCRIPTION_POINTER_SIGNATURE) ||
      !ChecksumIsValid (Rsdp, sizeof (EFI_ACPI_1_0_ROOT_SYSTEM_DESCRIPTION_POINTER)) ||
      (Rsdp->Revision < EFI_ACPI_2_0_ROOT_SYSTEM_DESCRIPTION_POINTER_REVISION) ||
      (Rsdp->Length < sizeof (*Rsdp)) ||
      !ChecksumIsValid (Rsdp, Rsdp->Length) ||
      (Rsdp->XsdtAddress == 0))
  {
    DEBUG ((DEBUG_ERROR, "%a: no valid libkrun RSDP at 0x%x\n", __func__, KRUN_ACPI_RSDP_ADDRESS));
    return EFI_NOT_FOUND;
  }

  Xsdt = (VOID *)(UINTN)Rsdp->XsdtAddress;
  if ((Xsdt->Signature != EFI_ACPI_2_0_EXTENDED_SYSTEM_DESCRIPTION_TABLE_SIGNATURE) ||
      (Xsdt->Length < sizeof (*Xsdt)) ||
      (((Xsdt->Length - sizeof (*Xsdt)) % sizeof (UINT64)) != 0) ||
      !ChecksumIsValid (Xsdt, Xsdt->Length))
  {
    return EFI_COMPROMISED_DATA;
  }

  Dsdt        = NULL;
  Entry       = (UINT64 *)(Xsdt + 1);
  EntryCount  = (Xsdt->Length - sizeof (*Xsdt)) / sizeof (*Entry);
  TableHandle = 0;

  for (Index = 0; Index < EntryCount; Index++) {
    Table = (VOID *)(UINTN)Entry[Index];
    if ((Table->Length < sizeof (*Table)) || !ChecksumIsValid (Table, Table->Length)) {
      return EFI_COMPROMISED_DATA;
    }

    Status = AcpiProtocol->InstallAcpiTable (
                             AcpiProtocol,
                             Table,
                             Table->Length,
                             &TableHandle
                             );
    if (EFI_ERROR (Status)) {
      return Status;
    }

    if (Table->Signature == EFI_ACPI_2_0_FIXED_ACPI_DESCRIPTION_TABLE_SIGNATURE) {
      Fadt = (VOID *)Table;
      if (Fadt->Header.Length <
          (OFFSET_OF (EFI_ACPI_2_0_FIXED_ACPI_DESCRIPTION_TABLE, XDsdt) +
           sizeof (Fadt->XDsdt)))
      {
        return EFI_COMPROMISED_DATA;
      }

      Dsdt = (VOID *)(UINTN)Fadt->XDsdt;
      if ((Dsdt != NULL) &&
          ((Dsdt->Length < sizeof (*Dsdt)) || !ChecksumIsValid (Dsdt, Dsdt->Length)))
      {
        return EFI_COMPROMISED_DATA;
      }
    }
  }

  if (Dsdt != NULL) {
    Status = AcpiProtocol->InstallAcpiTable (
                             AcpiProtocol,
                             Dsdt,
                             Dsdt->Length,
                             &TableHandle
                             );
    if (EFI_ERROR (Status)) {
      return Status;
    }
  }

  // Publish the original libkrun RSDP pointer directly to UEFI SystemTable.
  Status = gBS->InstallConfigurationTable (&gEfiAcpi20TableGuid, Rsdp);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  DEBUG ((DEBUG_INFO, "%a: successfully installed libkrun ACPI tables!\n", __func__));
  return EFI_SUCCESS;
}
